// <auto-generated/>
#ifndef _VERSION_FILE_H_
#define _VERSION_FILE_H_

#define szVerMajorMinor "3.10"
#define szVerMajorMinorBuildRev "3.10.1.2500"
#define rmj	3
#define rmm	10
#define rbd	1
#define rev	2500
#define szVerName	"BalExtensionExt Release"

#endif
